### ISSUE TITLE
Change SeasonDetails

### ISSUE THREAD

**Issue by IgorKvasn** [quaso/bookie#13]
please change `SeasonDetails`, so that instead of  `List<PlacesInfo>` it contains also information about the **names** of the places (right now `PlacesInfo` contains just count and type, but some time ago we agreed, that we will also provide names)
I need it in method `org.bookie.web.rest.WebResourceHandler#generateBookieConfig`

the information about the places can be either (sorry for the Javascript notation - is is much less verbose than Java :)
```
[
{name: 'kurt1', type: 'tennis'},
{name: 'kurt2', type: 'tennis'}
{name: 'kurt badm', type: 'badminton'}
]
```
or
```
[
{type: 'tennis', names: ['kurt1', ''kurt2']},
{type: 'badminton', names: ['kurt badm']}
]
```

it's up to you (basically I do not care about the format of the data - I will adjust to your needs)

**Comment by quaso** [comment]
Will return place name and id. Id is needed for creating a booking
