### ISSUE TITLE
Create API for available bookings

### ISSUE THREAD

**Issue by IgorKvasn** [quaso/bookie#9]
- for a given search criteria finds available courts that are empty and available for booking

example of server's response:
```
        [{
                date: <date>
            },
            {
                date: <date>
            },
            {
                date: <date>
            }
        ]
```
request parameters:
```
/api/search-booking?duration=1.5&timeStart=1200&timeEnd=1320&days%5B0%5D=Sat%20Dec%2010%202016%2000%3A00%3A00%20GMT%2B0100%20(CET)&days%5B1%5D=Sat%20Dec%2017%202016%2000%3A00%3A00%20GMT%2B0100%20(CET)
```
where:
 - `duration` => booking duration in hours - half hours are allowed, too
 - `timeStart`/`timeEnd` - in minutes
 - `days` - array of days

If for a given day/time, there are multiple courts/places empty - server should return only one entry

**Note: date/time format subject to change based on the agreement**

**Comment by quaso** [comment]
GET /api/booking/findFree?
duration (in minutes)
timeStart (in minutes)
timeEnd (in minutes)
days (list)
